# Generated by Django 4.2.4 on 2023-10-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
